# Generated by Django 5.1.1 on 2024-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Todo Name')),
                ('desciption', models.CharField(max_length=128, verbose_name='Todo Description')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('d', 'DONE')], max_length=1, verbose_name='Todo Status')),
            ],
        ),
    ]
