# Generated by Django 5.1.1 on 2024-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_desciption_todo_description_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Todo Description'),
        ),
    ]
